services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  web:
    build: .
    container_name: flask_web
    restart: always
    ports:
      - "80:8000"
    environment:
      - POSTGRESQL_CONNECTION_STRING=${POSTGRESQL_CONNECTION_STRING}
    depends_on:
      db:
        condition: service_healthy

  worker:
    build: .
    container_name: flask_worker
    restart: always
    command: python worker.py
    environment:
      - ENTSOE_API_KEY=${ENTSOE_API_KEY}
      - POSTGRESQL_CONNECTION_STRING=${POSTGRESQL_CONNECTION_STRING}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
